# Generated by Django 3.0.5 on 2020-05-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0003_auto_20200513_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullets',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bullets',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bullets',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Пули'),
        ),
        migrations.AddField(
            model_name='bullets',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Пули'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Тип оружия'),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Тип оружия'),
        ),
    ]
